### ISSUE TITLE
Setup a Meeting Time

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/counting-cockroaches#17]
See if @AdrielC is available to meet.

**Comment by dallin-cardon** [comment]
Ok @AdrielC says he can meet Thursday or Friday, any time. 

I'm free from 11 am until 4 pm on Thursday, and then after 5:30 pm.
I've got class from 11am until noon on Friday, but I'm free the rest of the day.

**Comment by marcdotson** [comment]
Awesome! @adrielc, @dallin-cardon, and @mdrewes, we'll meet Fridays at 1:30 pm for 30 minutes.
