### ISSUE TITLE
Schedule summer meeting

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/counting-cockroaches#26]
@dallin-cardon what would be a good time for you to meet over the summer?

**Comment by dallin-cardon** [comment]
Before 2 pm or after 7 pm on MW
Before 12 pm or after 6 pm on TTh
Anytime on Friday

**Comment by marcdotson** [comment]
Let's meet at 2 pm on Friday. @AdrielC, not sure what your plans are with school for the summer, but you are welcome to join us.

See you Friday!
